import test from 'node:test';
import assert from 'node:assert/strict';
import { filterListings, validateInquiry, toggleSelection } from '../lib/logic.mjs';
const fixtures=[{id:'a',type:'warehouse',name:'부산 상온',region:'부산',temperature:'상온',area:1650,district:'신항',tags:['도크'],service:'보관'}, {id:'b',type:'warehouse',name:'김해 창고',region:'김해',temperature:'냉장',area:660,district:'김해',tags:[],service:'식품'}, {id:'c',type:'partner',name:'부산 파트너',region:'부산',temperature:'상온',district:'신항',tags:['B2B'],service:'출고'}];
test('filters combine type, temperature, region, area and text',()=>{assert.deepEqual(filterListings(fixtures,{type:'warehouse',region:'부산',temperature:'상온',size:'1,000㎡ 이상',query:' 도크 '} ).map(x=>x.id),['a'])});
test('size filter excludes unknown area rather than treating it as zero',()=>{assert.deepEqual(filterListings(fixtures,{size:'1,000㎡ 미만'}).map(x=>x.id),['b'])});
test('search includes services and is case insensitive',()=>{assert.deepEqual(filterListings(fixtures,{query:'b2b'}).map(x=>x.id),['c'])});
test('unavailable temperature produces an empty result',()=>assert.equal(filterListings(fixtures,{temperature:'냉동'}).length,0));
test('comparison limits to three and removes selected item',()=>{assert.deepEqual(toggleSelection(['a','b','c'],'d'),['a','b','c']);assert.deepEqual(toggleSelection(['a','b'],'a'),['b']);assert.deepEqual(toggleSelection([],'a'),['a'])});
test('comparison does not mutate source array',()=>{const a=['a'];toggleSelection(a,'b');assert.deepEqual(a,['a'])});
const valid={name:'테스트',company:'테스트 회사',phone:'010-1234-5678',item:'아직 모름',consent:true};
test('unknown item and valid Korean phone are permitted',()=>assert.deepEqual(validateInquiry(valid),{}));
test('empty and whitespace-only contact fields are rejected',()=>{const errors=validateInquiry({...valid,name:' ',company:'',phone:'123',item:' '});assert.deepEqual(Object.keys(errors).sort(),['company','item','name','phone'])});
test('preparation-only acknowledgement is mandatory',()=>assert.ok(validateInquiry({...valid,consent:false}).consent));
test('partnership does not require item at first contact',()=>assert.deepEqual(validateInquiry({...valid,item:''},true),{}));
