'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Search, ArrowRight, RotateCcw, SlidersHorizontal } from 'lucide-react';
import { regions,listings } from '@/lib/data';
import { filterListings } from '@/lib/logic.mjs';
import { PageHeading,DemoNotice,CatalogCard,Empty } from './ui';
import { usePlatform } from './platform-provider';
export default function Catalog({type}){const [query,setQuery]=useState('');const [region,setRegion]=useState('전체 지역');const [temperature,setTemperature]=useState('전체 온도');const [size,setSize]=useState('전체 면적');const [sort,setSort]=useState('default');const {selected,toggle}=usePlatform();const warehouse=type==='warehouse';let results=filterListings(listings,{query,region,temperature,size,type});if(sort==='area') results=[...results].sort((a,b)=>(b.area||0)-(a.area||0));if(sort==='name')results=[...results].sort((a,b)=>a.name.localeCompare(b.name,'ko'));function reset(){setQuery('');setRegion('전체 지역');setTemperature('전체 온도');setSize('전체 면적');setSort('default')}
return <div className="page"><PageHeading eyebrow={warehouse?'FIND YOUR SPACE':'FIND YOUR PARTNER'} title={warehouse?'창고·물류센터':'물류사·3PL'} description={warehouse?'전국 시·도에서 희망 지역을 고르고, 필요한 물류거점 조건을 살펴보세요.':'품목과 온도, 필요한 서비스에 맞는 물류 파트너를 살펴보세요.'}><Link className="button button-outline" href="/consultation">맞는 후보 추천받기<ArrowUpRightSmall/></Link></PageHeading><DemoNotice>전국 지역 선택을 지원합니다. 현재 등록 자료는 부울경의 가상 예시이며, 다른 권역은 공급 자료 확보 후 등록합니다.</DemoNotice><div className="filter-panel"><div className="search-field"><Search size={19}/><input aria-label="지역, 시설 또는 서비스 검색" placeholder={warehouse?'지역, 시설명, 필요한 설비를 검색하세요':'지역, 업체명, 필요한 서비스를 검색하세요'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="검색어 지우기" onClick={()=>setQuery('')}>×</button>}</div><div className="filter-row"><span className="filter-label"><SlidersHorizontal size={16}/>상세 조건</span><label className="select-field"><span>지역</span><select value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(r=><option key={r}>{r}</option>)}</select></label><label className="select-field"><span>온도</span><select value={temperature} onChange={e=>setTemperature(e.target.value)}>{['전체 온도','상온','냉장','냉동'].map(t=><option key={t}>{t}</option>)}</select></label>{warehouse&&<label className="select-field"><span>면적</span><select value={size} onChange={e=>setSize(e.target.value)}>{['전체 면적','1,000㎡ 미만','1,000㎡ 이상'].map(t=><option key={t}>{t}</option>)}</select></label>}<button className="reset-button" onClick={reset}><RotateCcw size={15}/>초기화</button></div></div><div className="results-bar"><p>전체 <strong>{results.length}</strong>개 <span>· 예시 데이터</span></p><select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">기본 순</option><option value="name">이름 순</option>{warehouse&&<option value="area">면적 큰 순</option>}</select></div>{results.length?<div className="catalog-grid">{results.map(item=><CatalogCard key={item.id} item={item} selected={selected.includes(item.id)} onSelect={toggle}/>)}</div>:<Empty title="현재 선택 조건에 등록된 예시 후보가 없습니다." description="해당 지역의 실제 공급 유무를 뜻하지 않습니다. 상담 준비서에 희망 지역과 조건을 남겨보세요."><Link className="button button-dark" href="/consultation">상담 준비하기</Link><button className="button button-outline" onClick={reset}>필터 초기화</button></Empty>}<div className="inline-help"><div><strong>딱 맞는 조건이 보이지 않나요?</strong><p>아직 정해지지 않은 항목은 ‘모름’으로 시작할 수 있습니다.</p></div><Link href="/consultation">요구조건 알려주기<ArrowRight size={18}/></Link></div>{selected.length>0&&<div className="comparison-dock"><span><b>{selected.length}</b>개 후보를 담았습니다</span><Link className="button button-lime" href="/compare">비교함 보기<ArrowRight size={16}/></Link></div>}</div>}
function ArrowUpRightSmall(){return <ArrowRight size={17}/>}
