'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { LayoutDashboard, Warehouse, Truck, GitCompareArrows, BookOpen, ArrowUpRight, Plus, Menu, X, Handshake, Settings2, ArrowRight } from 'lucide-react';
import { usePlatform } from './platform-provider';
const navigation = [['/', '상담 시작',LayoutDashboard],['/warehouses','창고·물류센터',Warehouse],['/partners','물류사·3PL',Truck],['/compare','후보 비교함',GitCompareArrows],['/insights','물류 가이드',BookOpen]];
export default function Shell({ children }) {
 const path=usePathname(); const [open,setOpen]=useState(false); const {selected}=usePlatform();
 const current=navigation.find(([href])=>href==='/'?path==='/':path.startsWith(href))?.[1] || (path.startsWith('/consultation')?'상담 신청':path.startsWith('/admin')?'운영 워크스페이스':path.startsWith('/partnership')?'파트너 참여':'이용 안내');
 return <div className="app-shell"><a className="skip-link" href="#main">본문으로 이동</a><button className="mobile-menu" aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>{open&&<button aria-label="메뉴 닫기" className="nav-backdrop" onClick={()=>setOpen(false)}/>}
 <aside className={`sidebar ${open?'open':''}`}><Link className="brand" href="/" onClick={()=>setOpen(false)}><span className="brand-icon">↔</span><div>logiloop<span>로지루프 by 지음</span></div></Link><div className="nav-label">YOUR NEXT LOGISTICS</div><nav aria-label="주 메뉴">{navigation.map(([href,title,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={(href==='/'?path==='/':path.startsWith(href))?'nav-link active':'nav-link'} aria-current={(href==='/'?path==='/':path.startsWith(href))?'page':undefined}><Icon size={20}/><span>{title}</span>{href==='/compare'&&<b className="nav-count">{selected.length}</b>}</Link>)}</nav><div className="sidebar-bottom"><div className="region-note"><span className="live-dot"/>전국 물류 네트워크를 향해<p>지역의 경계를 넘어, 조건 중심으로.</p></div><Link className="side-secondary" href="/partnership" onClick={()=>setOpen(false)}><Handshake size={18}/>파트너 참여<ArrowUpRight size={16}/></Link><Link className="side-secondary" href="/admin" onClick={()=>setOpen(false)}><Settings2 size={18}/>운영 워크스페이스<span className="tiny-badge">DEMO</span></Link><div className="side-copyright">© LOGILOOP · 지음부동산중개법인(주)</div></div></aside>
 <div className="main-wrap"><header className="topbar"><div className="breadcrumb">플랫폼<span>/</span><strong>{current}</strong></div><div className="topbar-right"><span className="pilot-label"><span/>프리뷰</span><Link className="button button-dark button-small" href="/consultation"><Plus size={16}/>상담 신청</Link></div></header><main id="main" tabIndex={-1}>{children}</main><footer><div><strong>로지루프</strong><span>상담·비교·전환 지원 창구의 일원화</span></div><div><Link href="/about">서비스·역할 안내</Link><Link href="/privacy">개인정보 안내</Link><Link href="/consultation">상담 준비<ArrowRight size={14}/></Link></div></footer></div></div>;
}
