import type { Listing } from './types';

// 공개 화면 예시 7건. Supabase 연결 전·테스트 환경에서 사용하며, supabase/seed.sql과 같은 내용이다.
// All entries are fictional UI examples, not publicly available inventory.
export const seedListings: Listing[] = [
  { id: 'busan-01', name: '부산 신항권 상온 물류창고', region: '부산', district: '강서구 · 신항권', type: 'warehouse', temperature: '상온', area: 1650, capacity: '약 500평', price: '조건 협의', available: '입주일 확인 필요', status: '서류 확인 예시', tags: ['대형차 진입', '도크', '수출입 보관'], height: '9m', power: '협의', service: '컨테이너 입고 · 파렛트 보관', suitability: '신항을 이용하는 수입·유통 화주', limitation: '보세 여부 및 컨테이너 작업 시간 확인 필요', checks: ['예시 자료 등록', '서류 확인 예시', '현장 확인 대기', '화주 조건 확인 대기'], lat: 35.0985, lng: 128.8340 },
  { id: 'gimhae-01', name: '김해 제조 거점 독립형 창고', region: '김해', province: '경남', district: '진례면 · 제조 거점', type: 'warehouse', temperature: '상온', area: 990, capacity: '약 300평', price: '조건 협의', available: '입주일 확인 필요', status: '공급자 입력 예시', tags: ['독립 사용', '제조품 보관', '마당'], height: '7m', power: '협의', service: '원부자재 · 완제품 외부 보관', suitability: '공장 내 생산 공간이 필요한 제조 화주', limitation: '차량 회전 반경 및 바닥 하중 확인 필요', checks: ['예시 자료 등록', '서류 확인 대기', '현장 확인 대기', '화주 조건 확인 대기'], lat: 35.2436, lng: 128.7489 },
  { id: 'yangsan-01', name: '양산 냉장 보관 물류센터', region: '양산', province: '경남', district: '양산권 · 광역 배송', type: 'warehouse', temperature: '냉장', area: 2310, capacity: '약 700평', price: '조건 협의', available: '입주일 확인 필요', status: '현장 확인 예시', tags: ['냉장식품', '접안시설', '분할 임대 검토'], height: '8m', power: '협의', service: '냉장식품 보관', suitability: '양산 거점에서 냉장식품을 납품할 화주', limitation: '필요 온도와 구역별 가용 면적 별도 확인', checks: ['예시 자료 등록', '서류 확인 예시', '현장 확인 예시', '화주 조건 확인 대기'], lat: 35.3350, lng: 129.0372 },
  { id: 'changwon-01', name: '창원 산업단지 인근 창고', region: '창원', province: '경남', district: '성산구 · 산업단지권', type: 'warehouse', temperature: '상온', area: 660, capacity: '약 200평', price: '조건 협의', available: '입주일 확인 필요', status: '공급자 입력 예시', tags: ['부품 보관', '공장 인접', '독립 사용'], height: '6m', power: '협의', service: '제조 부품 보관', suitability: '생산 일정에 맞춘 외부 재고 거점', limitation: '위험물·중량물 취급 가능 여부 미확인', checks: ['예시 자료 등록', '서류 확인 대기', '현장 확인 대기', '화주 조건 확인 대기'], lat: 35.1983, lng: 128.7023 },
  { id: 'partner-01', name: '부산권 수출입 3PL 파트너', region: '부산', district: '강서구 · 신항권', type: 'partner', temperature: '상온', capacity: '물량별 확인', price: '물량 기준 견적', available: '수용 일정 확인 필요', status: '서류 확인 예시', tags: ['컨테이너 입고', '분할 납품', 'B2B'], service: '입고 · 보관 · 분할 출고 · 납품', suitability: '수입 후 여러 거래처에 분할 납품하는 화주', limitation: '최소 물량·차량·시간대별 작업 비용 확인 필요', checks: ['예시 자료 등록', '서류 확인 예시', '현장 확인 대기', '화주 조건 확인 대기'], lat: 35.0950, lng: 128.8500 },
  { id: 'partner-02', name: '김해권 제조 물류 파트너', region: '김해', province: '경남', district: '김해권 · 제조 물류', type: 'partner', temperature: '상온', capacity: '물량별 확인', price: '물량 기준 견적', available: '수용 일정 확인 필요', status: '공급자 입력 예시', tags: ['원부자재', '재고 보관', '정기 납품'], service: '외부 보관 · 정기 납품 · 회수', suitability: '생산 거점과 외부 창고를 연결하는 제조 화주', limitation: '피크 출고 능력과 재고 관리 방식 확인 필요', checks: ['예시 자료 등록', '서류 확인 대기', '현장 확인 대기', '화주 조건 확인 대기'], lat: 35.2285, lng: 128.8894 },
  { id: 'partner-03', name: '양산권 냉장식품 3PL 파트너', region: '양산', province: '경남', district: '양산권 · 식품 물류', type: 'partner', temperature: '냉장', capacity: '물량별 확인', price: '물량 기준 견적', available: '수용 일정 확인 필요', status: '현장 확인 예시', tags: ['냉장식품', '유통기한 관리', '소분 출고'], service: '냉장 보관 · 피킹 · 납품', suitability: '냉장식품 보관과 출고를 맡길 화주', limitation: '냉동수산·의약품 수용을 의미하지 않음', checks: ['예시 자료 등록', '서류 확인 예시', '현장 확인 예시', '화주 조건 확인 대기'], lat: 35.3100, lng: 129.0100 },
];
